# Jekyll configuration

encoding: utf-8
highlighter: rouge

includes:
  - feed.xml
  - feed.json

exclude:
  - .babelrc
  - Makefile
  - Gemfile
  - Gemfile.lock
  - vendor
  - package.json
  - yarn.lock
  - package-lock.json
  - webpack.config.js
  - node_modules
  - Dockerfile
  - docker_compose.yml

whitelist:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-redirect-from
  - jekyll-github-metadata
  
plugins:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-redirect-from
  #- jekyll-github-metadata

input_types:
- text
- textarea
- email
- date
- checkbox
- radio
- number
- submit

form_engines:
- cloudcannon
- formspree
- formbucket

collections:
  feeds:
    output: true
    permalink: /:collection/:path/

# Default Setting
# https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ""
      type: "feeds"
    values:
      layout: "feeds"

# Site link
base: _feeds/section
url: https://chetabahana.github.io
json_link: https://chetabahana.github.io/feed.json
slogan_link: https://chetabahana.com/info/tentang-89.html

# Site metadata
# https://help.github.com/articles/repository-metadata-on-github-pages/
repository: chetabahana/chetabahana.github.io
title: Chetabahana Project - A Way To Win The Market | GitHub Page
slogan: We are providing an Integrated Open Source Project about The World of e-Commerce.
keywords: chetabahana, projek, toko online, market leader, e-shop, eshop, scripts, open source, github page
description: Situs GitHub Toko Chetabahana | Projek prestisius dari Toko Chetabahana untuk e-Shop di Indonesia..
impressum: Chetabahana.com | Situs Belanja Jual-Beli Barang dan Promo Aneka Produk Fashion, Busana Muslim, Bayi & Anak-anak, Kecantikan, Tas, Sepatu, Peralatan Rumah Tangga, Elektronik, Makanan & Minuman Kemasan, dll.