encoding: utf-8
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from
collections:
  assets:
    output: true
    permalink: /:collection/:path
    redirect_from: /:collection/:path/:name
