# Jekyll configuration

encoding: utf-8
highlighter: rouge

includes:
  - feed.xml
  - feed.json

exclude:
  - .babelrc
  - Makefile
  - Gemfile
  - Gemfile.lock
  - vendor
  - package.json
  - yarn.lock
  - package-lock.json
  - webpack.config.js
  - node_modules
  - Dockerfile
  - docker_compose.yml

whitelist:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-redirect-from
  - jekyll-github-metadata
  
plugins:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-redirect-from
  #- jekyll-github-metadata

input_types:
- text
- textarea
- email
- date
- checkbox
- radio
- number
- submit

form_engines:
- cloudcannon
- formspree
- formbucket

collections:
  feeds:
    output: true
    permalink: /:collection/:path/

# Default Setting
# https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ""
      type: "feeds"
    values:
      layout: "feeds"

# Site info
url: https://chetabahana.github.io
base: _feeds/section
title: Chetabahana Project - A Way To Win The Market | GitHub Page

# GitHub metadata
# https://help.github.com/articles/repository-metadata-on-github-pages/
repository: chetabahana/chetabahana.github.io